title: 学记网
email: yangzhiyao@gmail.com
description: 学而时习之，不亦说乎

# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.xueji.org" # the base hostname & protocol for your site, e.g. http://example.com
page.comments: true
site.disqus.shortname: xueji
twitter_username: yangzhiyao
github_username:  yangzhiyao
repository: yangzhiyao/yangzhiyao.github.io
google_analytics: UA-50818870-1
JEKYLL_ENV: production

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"